### ISSUE TITLE
AttributeError when uploading?

### ISSUE THREAD

**Issue by ericswpark** [jkeifer/drf-chunked-upload#12]
Hi, I've set up this module with a project I'm working on and am trying to upload a file using a Python script (relevant portion attached below):

```python
  with open(file, 'rb') as file_raw:
      while chunk := file_raw.read(chunk_size):
          r = requests.put(upload_url, headers={
              "Authorization": "Token {}".format(token),
              "Content-Range": "bytes {}-{}/{}".format(current_chunk * chunk_size + 1,
                                                       current_chunk * chunk_size + len(chunk),
                                                       total_file_size)
          },
                           data={'file': chunk})
```

However, I'm getting an "AttributeError: 'str' object has no attribute 'size'" response. The trace points to the following code snippet:

https://github.com/jkeifer/drf-chunked-upload/blob/b6fcf85c39225617ae014d44f83e17470873cb34/drf_chunked_upload/views.py#L185

I'm guessing the error is occurring because the `chunk` object is being read in as a string and not in binary, so there is no size attribute. I don't know why the file is being read as a string; is there anything to fix in my code? Any help would be appreciated!

**Comment by ericswpark** [comment]
OK, so I tried patching the erroring part by changing `chunk.size` to `len(chunk)`. I think something is wrong with how the chunked data is sent to the Django server. Right before sending the data to the server, I checked the chunk size:

```python
with open(file, 'rb') as file_raw:
    while chunk := file_raw.read(chunk_size):
        print(len(chunk))
        r = requests.put(upload_url, headers={
            "Authorization": "Token {}".format(token),
            "Content-Range": "bytes {}-{}/{}".format(current_chunk * chunk_size + 1,
                                                     current_chunk * chunk_size + len(chunk),
                                                     total_file_size)
        },
                         data={'file': chunk})
```

The correct `chunk_size` of 10000 bytes is printed. However, I get the following response from the server:

```
File size doesn't match headers: file size is 9768 but 10000 reported
```

I don't understand how the chunk can be smaller after it's been transferred, so there must be a problem with how my code reads the chunks and sends them off (binary/text). @jkeifer sorry to bother you but do you have any examples on sending those chunks using Python?

**Comment by jkeifer** [comment]
The issue is that's a unicode string meant to represent bytes. It has to be converted into bytes in python 3 (the project I developed this for was exclusively python 2, so I never got to test the code with python 3), whereas in python 2 it is a unicode type object that has a size attribute.

So your change to `len(chunk)` is correct, but you'll also need to change the line where chunk is defined to encode the string as bytes, I think. That is, add `.encode('uft-8')` to the end of this line: https://github.com/jkeifer/drf-chunked-upload/blob/b6fcf85c39225617ae014d44f83e17470873cb34/drf_chunked_upload/views.py#L150

If it is easy for you to test that and it fixes the problem, please let me know. I don't have a great setup for testing this project anymore, so it would take me some time to get to the place where I could do so.

**Comment by ericswpark** [comment]
Hi, thank you for the reply!

> The issue is that's a unicode string meant to represent bytes. It has to be converted into bytes in python 3 (the project I developed this for was exclusively python 2, so I never got to test the code with python 3), whereas in python 2 it is a unicode type object that has a size attribute.
> 
> So your change to `len(chunk)` is correct, but you'll also need to change the line where chunk is defined to encode the string as bytes, I think. That is, add `.encode('uft-8')` to the end of this line:
> 
> https://github.com/jkeifer/drf-chunked-upload/blob/b6fcf85c39225617ae014d44f83e17470873cb34/drf_chunked_upload/views.py#L150

I made the change and tried uploading, but now get the opposite error - the chunk size is bigger after the transfer:

```
{"detail":"File size doesn't match headers: file size is 1018 but 1000 reported"}
```

I'm not sure how the encoding/decoding works, but my guess is the binary<->UTF-8 conversion results in a malformed binary chunk. I'll try other encoding methods and see if it'll work.

Also, if I make the chunk size smaller (about 500 bytes or so), I run into another error where the `ChunkedUpload` model lacks an `objects` attribute. Is this another Python2/3 problem?

**Comment by jkeifer** [comment]
I'm working on getting tests setup, because hey, if people are still using this package but are having problems then I can do better with testing. 😅 

However, as I was working through that, I realized what is likely happening here. I think you might be uploading the file incorrectly. It shouldn't use a JSON parser, as JSON will decode the bytes into a string, when you don't want that to happen. The whole thing with encoding is a red herring; it is a problem, but your bytes shouldn't be getting decoded into a string in the first place. I should have noticed that, but I haven't looked at this code in a couple years, so I didn't.

Anyway, in your `requests.put` rather than using the `data` parameter for the file chunk, use the `files` parameter (but also I think you need to use `data` to provide a file name):

```
        r = requests.put(upload_url, headers={
            "Authorization": "Token {}".format(token),
            "Content-Range": "bytes {}-{}/{}".format(current_chunk * chunk_size + 1,
                                                     current_chunk * chunk_size + len(chunk),
                                                     total_file_size)
        },
                         data={'filename': 'some_file'},
                         files={'file': chunk})
```

I will add a specification to limit the parser to only be the `MultiPartParser` once I get testing going.

**Comment by ericswpark** [comment]
I tried with the code snippet you gave me and it got past the chunk size error. However, it's now failing here:

https://github.com/jkeifer/drf-chunked-upload/blob/b6fcf85c39225617ae014d44f83e17470873cb34/drf_chunked_upload/views.py#L41

> AttributeError: type object 'ChunkedUpload' has no attribute 'objects'

Should I open another issue for this and close this one? The `files` workaround worked to solve the chunk size issue.

Edit: [Looking at the documentation](https://docs.djangoproject.com/en/3.2/ref/models/class/#objects), it seems like the `objects` attribute is not available for abstract models. Should I create another model that derives from the `ChunkedUpload` model?

**Comment by jkeifer** [comment]
Oh yes, that's correct. `ChunkedUpload` is an abstract class so migrations are not applied for it if the user is not using it in their project. But I realize this may not be the best UX when you do indeed want to use that class as-is.

**Comment by ericswpark** [comment]
Ah, okay. I actually tried to use the `django-chunked-upload` library and then switched to this library halfway through because it didn't work with REST, so my code didn't account for that. I noticed the model setup and what not differ slightly from the original project - are there any plans to follow the original project on the model setup? I'm currently trying to make the two projects match as much as possible in my fork so that `drf-chunked-upload` can be a drop-in replacement, but I don't know if you want to keep the two projects separate or not.

**Comment by jkeifer** [comment]
If I'm not mistaken, I forked this project relatively soon after django-chunked-upload was originally created. So there's been a bit of divergence over the years. As well, I created this specifically for another project I was working on, and did not think anyone would use it. So some of the choices were driven by the requirements of that project. Once I realized people were using this, I packaged it up on pypi, but haven't had a lot of time since then to maintain it as I have moved on to other things, none of them even django related anymore.

That said, people obviously still are using it despite its rough edges, and I think there's a lot of room for improvement. As well, I'm not beholden to the initial requirements, so besides preserving backward compatibility for existing users I don't have any strong feelings regarding UX or features.

Looking at django-chunked-upload now, I see there are separate abstract and concrete model classes, which seems like a good idea. It would be trivial to add a setting to enable/disable the concrete model class, which would help you out with your requirements.

It it might take me a bit of time to get to the place where I can make code changes with confidence, as I've mentioned with regard to a test env. For the time being, however, you could simply make the ChunkedUpload class not abstract.

**Comment by ericswpark** [comment]
> That said, people obviously still are using it despite its rough edges, and I think there's a lot of room for improvement. As well, I'm not beholden to the initial requirements, so besides preserving backward compatibility for existing users I don't have any strong feelings regarding UX or features.

Sounds good. I'll try and contribute back to the library whenever possible as I'm planning to use this for our Django project.

> Looking at django-chunked-upload now, I see there are separate abstract and concrete model classes, which seems like a good idea. It would be trivial to add a setting to enable/disable the concrete model class, which would help you out with your requirements.
> 
> It it might take me a bit of time to get to the place where I can make code changes with confidence, as I've mentioned with regard to a test env. For the time being, however, you could simply make the ChunkedUpload class not abstract.

I actually tried this and set the configuration option to make the `ChunkedUpload` model not abstract, but the problem is Django still won't create the tables for the model for some reason. So if I go into the admin panel and try and access the `ChunkedUpload` admin, I'd get a ProgrammingError, and same for trying to upload with chunks.

I've tried running `python manage.py migrate` but the script says there are no migrations, and `makemigrations` also doesn't work (no changes detected).

I'm going to try and make another model that inherits from the base `ChunkedUpload` model but right now the abstract setting doesn't behave as it should. Since this is a separate issue, I'll close this one off. Thank you for the help!

**Comment by jkeifer** [comment]
I just realized there is actually already a setting to enable/disable the abstract model, I'm glad you noticed that. 🤦 I told you, it has been awhile, I completely forgot about that.
