### ISSUE TITLE
The EXT of the file has been changed. Is it necessary to change the EXT back when downloading

### ISSUE THREAD

**Issue by isCopyman** [jkeifer/drf-chunked-upload#28]
The EXT of the file has been changed. Is it necessary to change the EXT back when downloading

**Comment by jkeifer** [comment]
Ideally you would have a view that used a url pattern ending with the uploaded file name (stored on the model, not the file name on disk), such that the client would write the file on its side using the original name, rather than serving the uploaded files directly.

Note that putting the application in the download path in this way is not the most performant option. If your files can be served by your reverse proxy as static files without the application’s involvement, that is better for performance but does not allow your application to do this mapping back to the original file name.

That said, this whole app is doing the inefficient thing of putting your app in the way of uploads, so maybe you don’t care for your purposes. But if your download-to-upload ratio is highly skewed towards downloads such that performance is more of a consideration there, then you might want to consider implementing something like a custom upload class that puts each file in a unique directory, such that the original filename can be preserved server-side without the risk of collisions, and then you can serve those uploads as static files directly from your reverse proxy.
